// Exports the ABIs the apps import. Run after `forge build`.
// Apps must import from @flippy/contracts, never copy an ABI into their own tree.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";

const CONTRACTS = ["FlippyGate", "MockToken", "MockSwap"];
mkdirSync("abi", { recursive: true });

const lines = ["// GENERATED by scripts/export-abi.mjs. Do not edit.", ""];
for (const name of CONTRACTS) {
  const artifact = JSON.parse(readFileSync(`out/${name}.sol/${name}.json`, "utf8"));
  writeFileSync(`abi/${name}.json`, JSON.stringify(artifact.abi, null, 2) + "\n");
}

const deployments = {};
for (const key of ["sepolia", "arc", "hedera"]) {
  const p = `deployments/${key}.json`;
  if (existsSync(p)) deployments[key] = JSON.parse(readFileSync(p, "utf8"));
}

const ts = [
  "// GENERATED by scripts/export-abi.mjs. Do not edit by hand.",
  ...CONTRACTS.map((n) => `import ${n}Abi from "../abi/${n}.json" with { type: "json" };`),
  "",
  `export const abis = { ${CONTRACTS.map((n) => `${n}: ${n}Abi`).join(", ")} } as const;`,
  ...CONTRACTS.map((n) => `export { ${n}Abi };`),
  "",
  `export const deployments = ${JSON.stringify(deployments, null, 2)} as const;`,
  "",
  "export type DeploymentKey = keyof typeof deployments;",
  "",
].join("\n");

mkdirSync("src-ts", { recursive: true });
writeFileSync("src-ts/index.ts", ts);
console.log(`exported ${CONTRACTS.length} ABIs and ${Object.keys(deployments).length} deployments`);
