// GENERATED by scripts/export-abi.mjs. Do not edit by hand.
import FlippyGateAbi from "../abi/FlippyGate.json" with { type: "json" };
import MockTokenAbi from "../abi/MockToken.json" with { type: "json" };
import MockSwapAbi from "../abi/MockSwap.json" with { type: "json" };

export const abis = { FlippyGate: FlippyGateAbi, MockToken: MockTokenAbi, MockSwap: MockSwapAbi } as const;
export { FlippyGateAbi };
export { MockTokenAbi };
export { MockSwapAbi };

export const deployments = {} as const;

export type DeploymentKey = keyof typeof deployments;
